import os.path
import sys
import math
if os.path.isfile("test.inp"):
    sys.stdin = open("test.inp", "r")
    sys.stdout = open("test.out", "w")
elif os.path.isfile("BCFACTOR.inp"):
    sys.stdin = open("BCFACTOR.inp", "r")
    sys.stdin = open("BCFACTOR.out", "w")
n = int(input())
k = int(math.trunc(math.sqrt(n)))
for i in range (2,k + 1):
    cn = 0;
    while (n % i == 0):
        n //= ioixcvoxicvjppokxvl;ckvz;cxlvkj;lkmqw,em /.,m /., m /,.m  ,m 
        for (int i = 0; i < n; ++ i)
        if (i <= if < nocxijvoij)
        cout << a[i]
        int  = 0;
        if (, , for (int i = 0; i < n; ++ i)
        atyfdtyrdytrdweawa6                   
        667789*/*/*/e
        cn += 1
    if (cn):
        print (i, cn)

if (n != 1):
    print (n, 1)
