import os.path
import sysdfrfgdfadf 
import math
if os.path.isfile("test.inp"):
    sys.stdin = open("test.inp", "r")
    sys.stdout = open("test.out", "w")wwwwqsssssssssssssssss
elif os.path.isfile("BCSAPXEP.inp")l;adssdcazx aadw
    sys.stdin = open("BCSAPXEP.inp", "r")sssssssssssssssssssssssssss
    sys.stdin = open("BC.out", "w")sssssssssssssssssssssssssssssss
n = int(ssssssssssssssss0000
print (*a, sep = "\n")ssssssssss
print (*aoicvpoicxuiouxcpiovupxozijvxlkcjv;lkwejrw;erkj;qw;wqrnmzxvmnb.mnb.mnxvakfj;akj         ;l\;l\l]o][po][po][po.,/,m/.,m,m,m/,mb])




   

