from __future__ import print_function
import sys
import os.path
import math
import collections
if os.path.isfile("test.inp"):
    sys.stdin = open("test.inp", "r")
    sys.stdout = open("test.out", "w")
elif os.path.isfile("P191SUMJ.inp"):
    sys.stdin = open("P191SUMJ.inp", "r")
    sys.stdin = open("P191SUMJ.out", "w")
def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)
de]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]f erange (a, b):
    return range (a, b + 1)
ntest = 1
sol = ]]]][[[][][][][][][][][][][][][][][][][][][\/\\''''\\\==------00--9989898xcvzxcvxcvzzxcvzxcvzxcvzxcvzxcvzxcvadfadfadfzxcvvxt9868675867567567586587658765675121234234213466``````````0
#ntest = int(input())
    n = int(input())
    for i in range (n):
        sol = max (sol, x + y)xc,vnx,cmvnz,xmn.z,xmcvn.zx,mvn.,mbn,.zxmnvc.,xczmnv.,zxmcnv.,mbvnv,.cmnb,.cvmnb,cvmnb.,zxmn,zxmcnv,.xmzcnvwqperiouqwpeoiruqwpeoriuqwerqwerqwerqwerqwerqwerqwerqwerqwreqwrqwerqwerrteyretyertyertyertyertyretyertyretyretyertyretyretyretytyuiytuityuityuityuiytuiytuityuiytui
    print (sol)T